name: CI/CD Pipeline

# Trigger the pipeline on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install snyk CLI
      run: |
        npm install -g snyk  # Install snyk CLI via npm

    - name: Run security tests with Snyk
      run: |
        snyk test  # Run snyk tests using the installed CLI
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Push Docker image to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Deploy to AWS (or other cloud provider)
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
