name: CI/CD Pipeline

# Trigger the pipeline on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Run security tests with Snyk
      uses: snyk/actions/python@master
      with:
        snyk_token: ${{ secrets.SNYK_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Push Docker image to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Deploy to AWS (or other cloud provider)
      run: |
        ./deploy.sh
